server:
  port: 8080
spring:
  application:
    name: mq-rabbitmq-producer
  rabbitmq:
    host: localhost
    port: 5672
    #注意：guest用户只能链接本地服务器 比如localhost  不可以连接远程服务器
    username: guest
    password: guest
    #虚拟主机 一台机器可能有很多虚拟主机 这里选择默认配置 / 即可
    virtual-host: /
    template:
      #失败重试
      retry:
        #是否开启失败重试
        enabled: true
        #第一次重试的间隔时长
        initial-interval: 10000ms
        #最长重试间隔，超过这个时间将不再重试
        max-interval: 300000ms
        #下次重试间隔的倍数，此处是2即下次重试间隔是上次的2倍
        multiplier: 2
      #缺省时的交换机名称，此处设置后，发送信息如果不指定交换机就会使用这个
      exchange: topic.exchange
#    publisher-confirms: true #确认消息已发送到交换机（Exchange），新版本jar,此设置已过时，替换成publisher-confirm-type: correlated
    #确认消息已发送到交换机（Exchange）选择交互类型为交互
    publisher-confirm-type: correlated
